export enum ActionType {
    SEARCH_REPOSITORY_ERROR = 'SEARCH_REPOSITORY_ERROR',
    SEARCH_REPOSITORY_SUCCESS = "SEARCH_REPOSITORY_SUCCESS",
    SEARCH_REPOSITORY = "SEARCH_REPOSITORY",
    SEARCH_BOOK = 'SEARCH_BOOK',
    SERACH_STAR_WARS = 'SERACH_STAR_WARS'
}